language: java
sudo: false
install: true
dist: precise

jdk: 
  - openjdk7
  - openjdk6
  - oraclejdk7
  - oraclejdk8

script:
  - mvn clean verify -B -e -V -Ptck-svn -Ptck-git

cache:
  directories:
    - '$HOME/.m2/repository'

branches:
    except:
        - gh-pages
